### Signup new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "email": "test5@example.com",
  "password": "12345",
  "name": "test5",
  "profilePicture": "00101010101100001101011101100101"
}

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "12345"
}

### Logout user
POST http://localhost:3000/users/logout

### Create new organization
POST http://localhost:3000/organizations/create
Content-Type: application/json

{
  "name": "test2 kft"
}

### Load all organizations accessible to current user
GET http://localhost:3000/organizations

### Load a specific organization accessible to current user
GET http://localhost:3000/organizations/10

### Add project owner to selected organization
### Can only run if you loaded an organization already.
POST http://localhost:3000/organizations/11
Content-Type: application/json

{
  "email": "test5@example.com"
}

### Create new project to selected organization.
### Can only run if you loaded an organization already.
POST http://localhost:3000/organizations/10/projects/create
Content-Type: application/json

{
  "name": "project3"
}

### List the selected organization's projects.
GET http://localhost:3000/organizations/10/projects

### Create task
POST http://localhost:3000/organizations/10/projects/13/tasks
Content-Type: application/json

{
  "name": "task3",
  "description": "task3 description",
  "deadline": "2023-06-22"
}

### List tasks
GET http://localhost:3000/organizations/10/projects/13/tasks

### Create subtask
POST http://localhost:3000/organizations/10/projects/13/tasks/1
Content-Type: application/json

{
  "name": "subtask2",
  "description": "subtask2 description",
  "deadline": "2023-06-22"
}

### List one task
GET http://localhost:3000/organizations/10/projects/13/tasks/5