### Signup new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "12345",
  "name": "test2",
  "profilePicture": "00101010101100001101011101100101"
}

### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "12345"
}

### Logout user
GET http://localhost:3000/users/logout

### Create new organization
POST http://localhost:3000/organizations/create
Content-Type: application/json

{
  "name": "minta1 kft"
}

### Load all organizations accessible to current user
GET http://localhost:3000/organizations

### Load a specific organization accessible to current user
GET http://localhost:3000/organizations/14

### Add project owner to organization
POST http://localhost:3000/organizations/14/add-project-owner
Content-Type: application/json

{
  "email": "test4@example.com"
}

### Add contributor to organization
POST http://localhost:3000/organizations/14/add-contributor
Content-Type: application/json

{
  "email": "test7@example.com"
}

### Create new project.
POST http://localhost:3000/organizations/1/projects/create
Content-Type: application/json

{
  "name": "project1"
}

### Add project owner to project
POST http://localhost:3000/organizations/14/projects/17/add-project-owner
Content-Type: application/json

{
  "email": "test3@example.com"
}

### Add contributor to project
POST http://localhost:3000/organizations/14/projects/17/add-contributor
Content-Type: application/json

{
  "email": "test2@example.com"
}

### List contributors
GET http://localhost:3000/organizations/14/projects/17/contributors

### Delete organization
DELETE http://localhost:3000/organizations/10

### List the selected organization's projects.
GET http://localhost:3000/organizations/16/projects

### List one project
GET http://localhost:3000/organizations/15/projects/18

### Delete project
DELETE http://localhost:3000/organizations/10/projects/13

### Create task
POST http://localhost:3000/organizations/1/projects/1/tasks
Content-Type: application/json

{
  "name": "task3",
  "description": "task3 description",
  "deadline": "2022-07-12",
  "assigneeId": 2
}

### List tasks
GET http://localhost:3000/organizations/1/projects/1/tasks

### Create subtask
POST http://localhost:3000/organizations/1/projects/1/tasks/9
Content-Type: application/json

{
  "name": "subSubtask3",
  "description": "subSubtask3 description",
  "deadline": "2022-04-12"
}

### List one task
GET http://localhost:3000/organizations/1/projects/1/tasks/2

### Delete task
DELETE http://localhost:3000/organizations/1/projects/1/tasks/1

### Add comment to task
POST http://localhost:3000/organizations/1/projects/1/tasks/2/add-comment
Content-Type: application/json

{
  "text": "ez egy 3 komment"
}

### Edit comment
PATCH http://localhost:3000/organizations/1/projects/1/tasks/2/edit-comment/11
Content-Type: application/json

{
  "text": "ez egy masik szerkesztett komment"
}

### Delete comment
DELETE http://localhost:3000/organizations/1/projects/1/tasks/2/delete-comment/10

### Get task logs
GET http://localhost:3000/organizations/1/projects/1/tasks/2/logs